# Site settings
title: Dr. Pavlo Bazilinskyy
email: p.bazilinskyy@tudelft.nl
description: Personal webpage of Dr. Pavlo Bazilinskyy
baseurl: ""
url: ""
affiliation: I am part of the <a href="https://www.tue.nl/en/research/research-groups/future-everyday/" target="_blank">Future Everyday</a> group at TU Eindhoven.

# Google analytics ID
google_analytics: UA-67250442-1

# Location info. (shown in footer)
location: >
  Department of Industrial Design<br/>
  P.O. Box 513<br/>
  5600 MB Eindhoven<br/>
  Netherlands<br/>

# Contact info. (shown in footer)
contact: >
    Contact me via email: <a href="mailto:p.bazilinskyy@tue.nl" target="_blank">p.bazilinskyy@tue.nl</a><br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research
  # - name: software
  # - name: team
  - name: education
  - name: volunteering

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
